"""Intent-driven keyword groups for LinkedIn lead discovery."""

from __future__ import annotations


LINKEDIN_KEYWORDS = [
    "doing this manually",
    "copy pasting all day",
    "so much repetitive work",
    "wasting time on",
    "takes forever to",
    "manually updating",
    "manually entering",
    "doing this by hand",
    "so behind on",
    "can't keep up with",
    "drowning in tasks",
    "too many things to track",
    "our process is broken",
    "workflow is a mess",
    "everything is scattered",
    "takes us 3 hours to",
    "looking for a tool to automate",
    "is there a way to automate",
    "how do people automate",
    "need to automate",
    "want to automate",
    "trying to automate",
    "any tool that can",
    "does anyone know how to automate",
    "looking for automation engineer",
    "hiring for automation",
    "need someone to automate",
    "looking for no-code developer",
    "need zapier expert",
    "need make.com help",
    "need n8n developer",
    "looking for workflow automation",
    "still using spreadsheets for",
    "using excel for everything",
    "our team still does this manually",
    "we have no system for",
    "we do everything manually",
    "no automation in place",
    "everything is manual",
]
